repos:
- repo: https://github.com/backplane/pre-commit-rust-hooks
  rev: v1.1.0
  hooks:
    - id: fmt
    - id: check
    - id: clippy
      args: ["--features", "ndarray-backend,candle-backend", "--all-targets", "--", "--deny", "warnings", "-W",  "clippy::redundant_clone"]
    - id: test
